### ISSUE TITLE
Support Django 1.7 / 1.8

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/django-overextends#16]
Test failing on 1.7 and 1.8:

```
ERROR: test_overextends (overextends.tests.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./../overextends/tests.py", line 93, in test_overextends
    html = get_template(self.unique_id).render(Context())
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 104, in render
    compiled_parent = self.get_parent(context)
  File "./../overextends/templatetags/overextends_tags.py", line 120, in get_parent
    template = self.find_template(parent, context)
  File "./../overextends/templatetags/overextends_tags.py", line 103, in find_template
    context[context_name][name].remove(remove_path)
ValueError: list.remove(x): x not in list
```

**Comment by al45tair** [comment]
It took me a couple of goes to figure out how to run the tests (not least because the `settings.py` needs a patch to make it work with Django 1.8).

It looks to me as if this is primarily a bug in the tests. What appears to be happening is that Django 1.8 (and possibly 1.7 as well) build their app registry *before* the test code edits `INSTALLED_APPS`, with the result that the only application Django knows about is `overextends`. I’m not sure how to fix that; the app registry doesn’t have any public API to add applications. The most sensible approach is probably to build the test in a static configuration, rather than trying to dynamically generate and add applications, but I think that’s something for you to decide as the package author.

There is also an additional bug in that calling `loader.load_template_source(name, [])` will actually find the template (if you check the Django sources, you’ll see that it does `if not template_dirs` rather than `if template_dirs is None` when deciding whether you specified template directories to search). Thus there should be an

    if not dirs:
        break

in the code in `overextends_tags.py`.

I've submitted another pull request to fix the problem of the tests not running because of the code in `settings.py`, and also to add the above change in `overextends_tags.py`. That doesn’t change the fact that the tests are going to continue breaking because of the application registry problem.

**Comment by al45tair** [comment]
Note that #17 does not completely fix this problem because a decision needs to be made about how to fix the test rig.

**Comment by stephenmcd** [comment]
Maybe if we somehow used `override_settings` decorator on `INSTALLED_APPS` we could maintain the current behaviour?

https://docs.djangoproject.com/en/1.8/topics/testing/tools/#overriding-settings

Also just discovered a new `modify_settings` API as for Django 1.7:

https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.SimpleTestCase.modify_settings

That matches more closely to what the tests are currently doing, and might be a lot easier to work with (since the decorators need to run at import time). I think it would be fine to drop support for Django 1.6 and earlier - what do you think?

**Comment by stephenmcd** [comment]
BTW thanks for going to all the trouble of diving deeply into this, it's really appreciated.

**Comment by jleclanche** [comment]
@stephenmcd Django 1.6 doesn't need to be supported imo since 1.7 is a LTS, yes. `modify_settings` looks good.

**Comment by stephenmcd** [comment]
@jleclanche want to try and finish it off then?

**Comment by jleclanche** [comment]
I can't take care of it for a while I'm afraid.

**Comment by stephenmcd** [comment]
No problem! I just assumed you needed it now.
